version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - .:/app/frontend
      - /app/frontend/node_modules
    environment:
      - NODE_ENV=development
